### ISSUE TITLE
Captcha Error

### ISSUE THREAD

**Issue by AceHack** [Woogo-io/stockx-api#1]
I'm getting the following error

Error: Status code error 403 - Response: {"appId":"PX16uD0kOF","jsClientSrc":"/16uD0kOF/init.js","firstPartyEnabled":true,"vid":"","uuid":"712876af-3b52-11ec-8fe5-677768516a53","hostUrl":"/16uD0kOF/xhr","blockScript":"/16uD0kOF/captcha/captcha.js?a=c&u=712876af-3b52-11ec-8fe5-677768516a53&v=&m=0"}

**Comment by GautheyValentin** [comment]
Hi,

You tried to scrap from home computer or from server ?
Try to use proxy to escape captcha

**Comment by AceHack** [comment]
Home computer and what do you mean by use proxy?

**Comment by GautheyValentin** [comment]
It was a User Agent problem, i thinks it's fix
